name: py

on:
  # schedule:
  #   - cron:  '0 */3 * * *' # Edit this cron to set the frequency. Here it is set to every 3 hours (8 times a day)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
          pip install TwitterApi
      - name: execute py script # run file
        run: |
          python tweet_from_collection.py
